# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
#https://cloud.google.com/solutions/cicd-pipeline-for-data-processing
steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sample-proj", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/sample-proj"]
    # deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "sample-proj",
        "--image",
        "gcr.io/$PROJECT_ID/sample-proj",
        "--region",
        "us-east1",
        "--allow-unauthenticated",
      ]
    env:
      - "PORT=8080"
images:
  - gcr.io/$PROJECT_ID/sample-proj
