apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: sample-proj
spec:
  selector:
    matchLabels:
      app: sample-proj
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: cloud-test
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/cloud-computing-302919/sample-proj
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
              # If your cluster config does not include a dns service, then to
              # instead access environment variables to find service host
              # info, comment out the 'value: dns' line above, and uncomment the
              # line below:
              # value: env
          ports:
            - containerPort: 8080
